/**************************************************************************
* Copyright (C) 2018 PowerTech Engineering AS <post@pt-eng.no>
*
* This code may not be distributed, used or sold without explicit
* written permission from PowerTech Engineering AS.
*********************************************************************/

#pragma once

#include "wide/wide_api.h"
#include "external_lib_structs.h"

/* The Prototypes */
BOOL BACNETAPI_ACTIONRESULTinit(BACNETAPI_ACTIONRESULTtyp* inst, BOOL bRetain);
BOOL BACNET_INTERNAL_DATAinit(BACNET_INTERNAL_DATAtyp* inst, BOOL bRetain);
BOOL BACNET_STRUCT_VIEW_OBJECTinit(BACNET_STRUCT_VIEW_OBJECTtyp* inst, BOOL bRetain);
BOOL BACNET_ANY_OBJECTinit(BACNET_ANY_OBJECTtyp* inst, BOOL bRetain);
BOOL BACNETSTATUSFLAGSinit(BACNETSTATUSFLAGStyp* inst, BOOL bRetain);
BOOL BACNETAPI_GETRESULTinit(BACNETAPI_GETRESULTtyp* inst, BOOL bRetain);
BOOL BACNETDATEinit(BACNETDATEtyp* inst, BOOL bRetain);
BOOL BACNETTIMEinit(BACNETTIMEtyp* inst, BOOL bRetain);
BOOL BACNETDATETIMEinit(BACNETDATETIMEtyp* inst, BOOL bRetain);
BOOL BACNETACKEDINFOinit(BACNETACKEDINFOtyp* inst, BOOL bRetain);
BOOL BACNETLIMITENABLEinit(BACNETLIMITENABLEtyp* inst, BOOL bRetain);
BOOL BACNETEVENTTRANSITIONBITSinit(BACNETEVENTTRANSITIONBITStyp* inst, BOOL bRetain);
BOOL BACNET_ANALOG_VALUEinit(BACNET_ANALOG_VALUEtyp* inst, BOOL bRetain);
BOOL BACNET_BINARY_VALUEinit(BACNET_BINARY_VALUEtyp* inst, BOOL bRetain);
BOOL BACNET_CALENDARinit(BACNET_CALENDARtyp* inst, BOOL bRetain);
BOOL BACNET_CHARSTRING_VALUEinit(BACNET_CHARSTRING_VALUEtyp* inst, BOOL bRetain);
BOOL BACNET_DEVICE_OBJECTinit(BACNET_DEVICE_OBJECTtyp* inst, BOOL bRetain);
BOOL BACNETOBJECTIDinit(BACNETOBJECTIDtyp* inst, BOOL bRetain);
BOOL BACNETDEVICEOBJPROPERTYREFinit(BACNETDEVICEOBJPROPERTYREFtyp* inst, BOOL bRetain);
BOOL BACNET_LOOPinit(BACNET_LOOPtyp* inst, BOOL bRetain);
BOOL BACNET_MULTISTATE_VALUEinit(BACNET_MULTISTATE_VALUEtyp* inst, BOOL bRetain);
BOOL BACNET_NOTIFICATION_CLASSinit(BACNET_NOTIFICATION_CLASStyp* inst, BOOL bRetain);
BOOL BACNET_SCHEDULEinit(BACNET_SCHEDULEtyp* inst, BOOL bRetain);
BOOL BACNET_STATUS_INFO_OBJECTinit(BACNET_STATUS_INFO_OBJECTtyp* inst, BOOL bRetain);
BOOL BACNET_TRENDLOGinit(BACNET_TRENDLOGtyp* inst, BOOL bRetain);
BOOL BACNETDEVICEADDRESSinit(BACNETDEVICEADDRESStyp* inst, BOOL bRetain);
BOOL BACNETWEEKNDAYinit(BACNETWEEKNDAYtyp* inst, BOOL bRetain);
BOOL BACNET_FILE_OBJECTinit(BACNET_FILE_OBJECTtyp* inst, BOOL bRetain);
BOOL BACNETAPI_GETPROPSBYID_ITEMinit(BACNETAPI_GETPROPSBYID_ITEMtyp* inst, BOOL bRetain);
BOOL BACNETAPI_GETPROPSBYIDinit(BACNETAPI_GETPROPSBYIDtyp* inst, BOOL bRetain);
BOOL BACNETAPI_XMLinit(BACNETAPI_XMLtyp* inst, BOOL bRetain);
