/**************************************************************************
* Copyright (C) 2018 PowerTech Engineering AS <post@pt-eng.no>
*
* This code may not be distributed, used or sold without explicit
* written permission from PowerTech Engineering AS.
*********************************************************************/

#pragma once

#include "wide/wide_api.h"
#include "external_lib_structs.h"


/* The Prototypes */
BOOL BACNETAPI_ACTIONGETSTATUS(DWORD ACTIONHANDLEIDparam, BACNETAPI_ACTIONRESULTtyp *OUTACTIONRESULTparam);
;
BACNET_ANY_OBJECTtyp *BACNETAPI_CREATEOBJECT(char* NAMEparam, DWORD OBJECTIDparam, INT OBJECTTYPEparam, BACNET_STRUCT_VIEW_OBJECTtyp *PARENTparam, BOOL ADDTODBparam);
;
BOOL BACNETAPI_DELETEOBJECT(BACNET_ANY_OBJECTtyp *POBJECTparam);
;
BOOL BACNETAPI_GETBYID(DWORD DEVICEIDparam, DWORD OBJECTIDparam, INT OBJECT_TYPEparam, INT OBJECT_PROPERTYparam, DWORD ARRAY_INDEXparam, INT VALUETYPEparam, INT VALUEDIMparam, BYTE *VALUEBUFFERparam, DWORD VALUEBUFFERSIZEparam, BOOL *RESULTDATAparam, BACNETAPI_GETRESULTtyp *OUTRESULTDATAparam);
;
BOOL BACNETAPI_GETBYSTR(char* DEVICENAMEparam, char* OBJECTNAMEparam, INT OBJECT_TYPEparam, INT OBJECT_PROPERTYparam, DWORD ARRAY_INDEXparam, INT VALUETYPEparam, INT VALUEDIMparam, BYTE *VALUEBUFFERparam, DWORD VALUEBUFFERSIZEparam, BOOL *RESULTDATAparam, BACNETAPI_GETRESULTtyp *OUTRESULTDATAparam);
;
BACNET_ANY_OBJECTtyp *BACNETAPI_GETOBJECT(DWORD DWINSTANCEparam, INT OBJECTTYPEparam);
;
BACNET_ANY_OBJECTtyp *BACNETAPI_GETOBJECTBYNAME(char* STRNAMEparam, INT OBJECTTYPEparam);
;
void BACNETAPI_GETPROPSBYID(BACNETAPI_GETPROPSBYIDtyp* inst);
BOOL BACNETAPI_INVALIDATEOBJECTS(BOOL DELETEDYNAMICOBJECTSparam);
;
INT BACNETAPI_PROCESS(DWORD DWMAXTIMEparam);
;
BOOL BACNETAPI_REGOBJECT(BACNET_ANY_OBJECTtyp *POBJECTDATAparam, DWORD OBJECTSIZEparam, BACNET_STRUCT_VIEW_OBJECTtyp *PPARENTOBJECTparam);
;
DWORD BACNETAPI_SELECTOBJECTS(BACNET_ANY_OBJECTtyp **POBJECTARRAYparam, DWORD DWOBJECTARRAYSIZEparam, INT FILTERparam);
;
BOOL BACNETAPI_SETPERSISTBUFFER(BYTE *PBUFFERparam, DWORD DWBUFFERSIZEparam);
;
BOOL BACNETAPI_START(WORD WPORTparam, char* STRINTERFACENAMEparam, DWORD DWDEVICEIDparam, char* STRDEVICENAMEparam);
;
BOOL BACNETAPI_STOP(void);
;
DWORD BACNETAPI_VERSION(void);
;
DWORD BACNETAPI_WRITEREQUESTBYID(DWORD DEVICEIDparam, DWORD OBJECTIDparam, INT VALUETYPEparam, INT VALUEDIMparam, BYTE *VALUEBUFFERparam, DWORD VALUEBUFFERSIZEparam, INT OBJECT_TYPEparam, INT OBJECT_PROPERTYparam, DWORD ARRAY_INDEXparam, INT WRITEPRIORITYparam, INT APPLICATIONTAGparam);
;
DWORD BACNETAPI_WRITEREQUESTBYSTR(char* DEVICENAMEparam, char* OBJECTNAMEparam, INT VALUETYPEparam, INT VALUEDIMparam, BYTE *VALUEBUFFERparam, DWORD VALUEBUFFERSIZEparam, INT OBJECT_TYPEparam, INT OBJECT_PROPERTYparam, DWORD ARRAY_INDEXparam, INT WRITEPRIORITYparam, INT APPLICATIONTAGparam);
;
void BACNETAPI_XML(BACNETAPI_XMLtyp* inst);
